### ISSUE TITLE
Error "Database is required"

### ISSUE THREAD

**Issue by gvugt** [zeekoe/bluebird#3]
When I run the bluebird script it returns this error when trying to write the data to the influx server: 

The logging:
Gapfiller fresh start.
Gapfiller next window: 2024-02-13T19:44:20.810739035+01:00[Europe/Amsterdam] - 2024-02-13T21:44:30.811684151+01:00[Europe/Amsterdam]
Retrieving token
-1.0 2024-02-13T21:44:21.318718344: Exception, retry count: 1
database is required
-1.0 2024-02-13T21:44:51.394642458: Exception, retry count: 2
database is required

-------------
On the influxdb side I see this in the logging:
[httpd] 172.17.0.1 - test [13/Feb/2024:20:44:21 +0000] "POST /write?db=&rp=autogen&precision=n&consistency=one HTTP/1.1" 400 33 "-" "okhttp/4.10.0" aa2bd783-cab0-11ee-8001-0242ac110003 196
--> db= ... so there is no database being called?

My /etc/bluebird.config file looks like this:
bluebird.username=xxx@xxx.com
bluebird.password=xxx
bluebird.logurl=https://api.weheat.nl/api/v1/heat-pumps/CODE/logs/latest

influxdb.bluebird.database=bluebird
influxdb.bluebird.measurement=bluebird
influxdb.url=http://localhost:8086
influxdb.username=test
influxdb.password=testtest

**Comment by gvugt** [comment]
Great it is working now!

**Comment by zeekoe** [comment]
Mooi, veel plezie ermee! :)
